### ISSUE TITLE
Diagrama de casos de uso del sistema

### ISSUE THREAD

**Issue by stg1004** [psv1002/SoftwarePractica#1]

**Comment by bam1006** [comment]
Ya está subido el documento con el diagrama de casos de uso.

**Comment by psv1002** [comment]
Vale acabo de revisar el diagrama de casos de uso del Sistema y yo lo veo super completo y bien, entonces por mi ya puedes subir esa parte al PDF del trabajo.

**Comment by LorenaNerinG** [comment]
Yo también me lo leí, lo he repasado y pienso igual que Paula, esta genial.

**Comment by stg1004** [comment]
Genial, lo dejamos así entonces.
