### ISSUE TITLE
Catálogo de requisitos funcionales

### ISSUE THREAD

**Issue by stg1004** [psv1002/SoftwarePractica#2]

**Comment by bam1006** [comment]
Hola, ¿podéis revisar el documento de los requisitos funcionales?, ¡ya está subido!

**Comment by LorenaNerinG** [comment]
Revisado, esta perfecto!

**Comment by psv1002** [comment]
Me gusta mucho como ha quedado, vale vete subiendo lo que hicimos en clase todas y así lo vamos metiendo al PDF
