### ISSUE TITLE
Especificación de los actores del sistema

### ISSUE THREAD

**Issue by stg1004** [psv1002/SoftwarePractica#5]

**Comment by psv1002** [comment]
Vale son todas las tablas que hicimos en clase, perfecto súbelo

**Comment by LorenaNerinG** [comment]
Antes de subirlo, hay que arreglar una cosilla...

**Comment by stg1004** [comment]
Por mí está todo correcto, nada más que añadir

**Comment by bam1006** [comment]
¡Ya está subido chicas!
