### ISSUE TITLE
Prototipo de pantallas casos de uso

### ISSUE THREAD

**Issue by stg1004** [psv1002/SoftwarePractica#6]

**Comment by LorenaNerinG** [comment]
Que os parecen?

**Comment by psv1002** [comment]
Los prototipos han quedado super bien los que yo ví, subid todos por aquí para ver como han quedado todos juntos.

**Comment by stg1004** [comment]
Ok

**Comment by bam1006** [comment]
Acabo de subirlos, ¡yo creo que han quedado muy bien!

**Comment by psv1002** [comment]
Han quedado super chulos la verdad, me encantan!!!
